routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');
# Operator
Route::resource('operator', 'OperatorController');
Route::post('operator/detail', 'OperatorController@detail');

# Product Type
Route::resource('product-type', 'ProductTypeController');
Route::post('product-type/detail', 'ProductTypeController@detail');

# Product
Route::resource('product', 'ProductController');
Route::post('product/detail', 'ProductController@detail');

# Sale
Route::resource('sale', 'SaleController');
Route::post('sale/detail', 'SaleController@detail');

# Purchase
Route::resource('purchase', 'PurchaseController');

app/Operator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Operator extends Model
{
    use Uuids;

    public $incrementing = false;

   	public $fillable = ['name'];
    
    public function products(){
    	return $this->hasMany('App\Product');
    }
    
}

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Operator;

use Yajra\Datatables\Datatables;

use Yajra\Datatables\Html\Builder;


class OperatorController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $data = Operator::all();
            return Datatables::of($data)
                ->addColumn('action', function($operator){
                    return view('datatables._action', [
                        'id' =>$operator->id,
                        'url' => url('operator'),
                        'edit' => true,
                    ]);
                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data' => 'name', 'name'=>'name', 'title'=>'Name'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);
        return view('operators.index')->with(compact('html'));
    }

    public function store(Request $request)
    {
        if ($request->ajax()) {
            $data = Operator::create([
                'name' => strtoupper($request->name),
                ]);
            return $data;
        }
    }
    public function update(Request $request)
    {
        if ($request->ajax()) {
            $data = Operator::find($request->id);
            $data->name = strtoupper($request->name);
            $data->save();

            return $data;
        }
    }

    public function detail(Request $request)
    {
        if ($request->ajax()) {
            $id = $request->input('id');
            $data = Operator::find($id);
            return $data;
        }
    }

    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {
            $data = Operator::destroy($request->id);
            if ($data) {
                return $data;
            }
        }
    }
}

resources/views/operators/_modal.blade.php
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
             <form id="modal-form">
                {{ csrf_field() }}
                <input type="hidden" name="id" id="id">
                <input type="hidden" name="form-type" id="form-type" value="add">
              <div class="form-group">
                <label for="name">Nama:</label>
                <input type="name" class="form-control" name="name">
              </div>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-save">Simpan</button>
      </div>
    </div>

  </div>
</div>

resources/views/operators/index.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Data Operator</strong>
&nbsp;<div class="btn btn-success btn-xs btn-add" style="margin-bottom: 10px;" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i></div>
                </div>
                <div class="panel-body">
                {!! $html->table(['class'=>'table-striped']) !!}
                </div>
            </div>
        </div>
    </div>
</div>
    @include('operators._modal')
@endsection

@section('script')
{!! $html->scripts() !!}
<script>
    var formType = $("#form-type");
    var inputName = $("[name=name]");
    var inputId = $("#id");
    var modalTitle  = $(".modal-title");
    var btnSave = $(".btn-save");
    var _token = $("[name=_token]").val();
    var me = $("#modal-form");

     // when adding some data
    $(".btn-add").click(function() {
        modalTitle.html("Tambah Data");
        inputName.val("");

        btnSave.prop('disabled', false);
        formType.val("add");
    });

    // when click edit button
    $(document).on("click", ".edit-modal", function () {
        btnSave.prop('disabled', false);
         var id     = $(this).data('id');
         formType.val('update');
         $.ajax({
            dataType: "json",
            url: "{{ url('operator/detail') }}",
            data: {
                id:id,
                _token: _token
            },
            type : "post",
            success: function(data){
                inputName.val(data.name);
                inputId.val(data.id);
                modalTitle.html('Update '+data.name);
            }
        });

    });

    // process data
    btnSave.click(function() {

        btnSave.prop('disabled',true);
        btnSave.html('Sedang diproses..');
        url = "{{ route('operator.store') }}";
        method = 'post';
        if(formType.val() != "add") {
            url = "{{ url('operator/update') }}";
            method = 'put';
        }

        $.ajax({
            dataType: "json",
            url: url,
            data: me.serialize(),
            type : method,
            success: function(data){
                btnSave.prop('disabled',false);
                btnSave.html('Simpan');
                swal({
                    type:"success",
                });
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                $("#myModal").modal('toggle');

                // reset
               // reset
                me[0].reset();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
               btnSave.prop('disabled',false);
            }
        });

    });

    function deleteData(id){
        swal({
          title: 'Hapus Data!',
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes'
        }).then(function () {
            processDelete(id)
        }, function (dismiss) {
          // dismiss can be 'cancel', 'overlay',
          // 'close', and 'timer'
          if (dismiss === 'cancel') {
            swal(
              'Cancelled',
              '',
              'error'
            )
          }
        })
    }

    function processDelete(id) {
        var url = '{{ url("operator")}}' + '/' + id;
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            dataType: "json",
            url: url,
            type : "DELETE",
            data : {
                _token : $('meta[name="csrf-token"]').attr('content'),
                id : id
            },
            success: function(data){
                swal(
                  'Deleted!',
                  'Your file has been deleted.',
                  'success'
                )
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
            }
        });
    }
</script>
@endsection