routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');
# Operator
Route::resource('operator', 'OperatorController');
Route::post('operator/detail', 'OperatorController@detail');

# Product Type
Route::resource('product-type', 'ProductTypeController');
Route::post('product-type/detail', 'ProductTypeController@detail');

# Product
Route::resource('product', 'ProductController');
Route::post('product/detail', 'ProductController@detail');

# Sale
Route::resource('sale', 'SaleController');
Route::post('sale/detail', 'SaleController@detail');

# Purchase
Route::resource('purchase', 'PurchaseController');

app/Product.php
<?php

namespace App;
use DB;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use Uuids;

    public $incrementing = false;

   	public $fillable = ['name', 'operator_id', 'product_type_id','qty', 'buy_price', 'sell_price'];

   	public function operator()
   	{
   		return $this->belongsTo('App\Operator');
   	}

    public function productType()
    {
      return $this->belongsTo('App\productType');
    }

    public function sales()
    {
      return $this->hasMany('App\Sale');
    }

    public function purchase()
    {
      return $this->hasMany('App\Purchase');
    }
    
   	public static function getTotal(){
   		$totalData = DB::table('products')
   						->select(DB::raw("sum((qty*buy_price)) as total"))
   						->first();
   		return $totalData->total;
   	}

    public static function addStock($id, $qty)
    {
        $product = self::find($id);
        $product->qty = $product->qty + $qty;
        $product->save();
        return $product;
    }

    public static function reduceStock($id, $qty)
    {
        $product = self::find($id);
        $product->qty = $product->qty - $qty;
        $product->save();
        return $product;
    }
}

app/ProductType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    use Uuids;

    public $incrementing = false;

   	public $fillable = ['name'];

   	public function products(){
    	return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Product;
use Yajra\Datatables\Datatables;

use Yajra\Datatables\Html\Builder;


class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $data = Product::with('operator','productType');
            return Datatables::of($data)
                ->addColumn('action', function($productType){
                    return view('datatables._action', [
                        'id' =>$productType->id,
                        'url' => url('product'),
                        'edit' => true,
                    ]);

                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data' => 'name', 'name'=>'name', 'title'=>'Name'])
            ->addColumn(['data' => 'buy_price', 'name'=>'buy_price', 'title'=>'Harga Beli'])
            ->addColumn(['data' => 'sell_price', 'name'=>'sell_price', 'title'=>'Harga Jual'])
            ->addColumn(['data' => 'qty', 'name'=>'qty', 'title'=>'Qty'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);
        return view('products.index')->with(compact('html'));
            return $html;
    }

    public function store(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::create([
                'name' => strtoupper($request->name),
                'operator_id' => $request->operator_id,
                'product_type_id' => $request->product_type_id,
                'qty' => $request->qty,
                'buy_price' => $request->buy_price,
                'sell_price' => $request->sell_price,
            ]);
            return $data;
        }
    }
    public function update(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::find($request->id);
            $data->name = strtoupper($request->name);
            $data->operator_id = $request->operator_id;
            $data->product_type_id = $request->product_type_id;
            $data->qty = $request->qty;
            $data->buy_price = $request->buy_price;
            $data->sell_price = $request->sell_price;
            $data->save();

            return $data;
        }
    }

    public function detail(Request $request)
    {
        // if ($request->ajax()) {
            $id = $request->input('id');
            $data = Product::find($id);
            return $data;
        // }
    }

    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {
            $data = Product::destroy($request->id);
            if ($data) {
                return $data;
            }
        }
    }
}

resources/views/products/_modal.blade.php
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
             <form id="modal-form">
                {{ csrf_field() }}
                <input type="hidden" name="id" id="id">
                <input type="hidden" name="form-type" id="form-type" value="add">
              <div class="form-group">
                <label for="name">Nama:</label>
                <input type="text" class="form-control" name="name">
              </div>
              <div class="form-group">
                <label for="name">Operator:</label>
                {!! Form::select('operator_id', [''=>'']+App\Operator::pluck('name','id')->all(), null, [
                    'class'=>'js-selectize',
                    'placeholder' => 'Pilih Operator']) !!}
              </div>
              <div class="form-group">
                <label for="name">Jenis Produk:</label>
                {!! Form::select('product_type_id', [''=>'']+App\ProductType::pluck('name','id')->all(), null, [
                    'class'=>'js-selectize',
                    'placeholder' => 'Pilih Jenis Produk']) !!}
              </div>
              <div class="form-group">
                <label for="name">Qty:</label>
                {!! Form::number('qty', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>
              <div class="form-group">
                <label for="name">Harga Beli:</label>
                {!! Form::number('buy_price', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>
              <div class="form-group">
                <label for="name">Harga Jual:</label>
                {!! Form::number('sell_price', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>

            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-save">Simpan</button>
      </div>
    </div>

  </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Data Produk &nbsp; <div class="btn btn-success btn-xs btn-add" style="margin-bottom: 10px;" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Tambah</div>
                </div>
                <div class="panel-body">
                     {!! $html->table(['class'=>'table-striped']) !!}
                </div>
            </div>
        </div>
    </div>
</div>
    @include('products._modal')
@endsection

@section('script')
{!! $html->scripts() !!}
<script>
    var formType = $("#form-type");
    var inputName = $("[name=name]");
    var inputId = $("#id");
    var modalTitle  = $(".modal-title");
    var btnSave = $(".btn-save");
    var _token = $("[name=_token]").val();
    var me = $("#modal-form");

     // when adding some data
    $(".btn-add").click(function() {
        modalTitle.html("Tambah Data");
        me[0].reset();

        btnSave.prop('disabled', false);
        formType.val("add");
    });

    // when click edit button
    $(document).on("click", ".edit-modal", function () {
        btnSave.prop('disabled', false);
         var id     = $(this).data('id');
         formType.val('update');
         $.ajax({
            dataType: "json",
            url: "{{ url('product/detail') }}",
            data: {
                id:id,
                _token: _token
            },
            type : "post",
            success: function(data){
                $("[name=name]").val(data.name);
                $("[name=operator_id]").val(data.operator_id);
                $("[name=product_type_id]").val(data.product_type_id);
                $("[name=qty]").val(data.qty);
                $("[name=buy_price]").val(data.buy_price);
                $("[name=sell_price]").val(data.sell_price);
                inputId.val(data.id);
                modalTitle.html('Update '+data.name);
            }
        });

    });

    // process data
    btnSave.click(function() {

        btnSave.prop('disabled',true);
        btnSave.html('Sedang diproses..');
        url = "{{ route('product.store') }}";
        method = 'post';
        if(formType.val() != "add") {
            url = "{{ url('product/update') }}";
            method = 'put';
        }

        $.ajax({
            dataType: "json",
            url: url,
            data: me.serialize(),
            type : method,
            success: function(data){
                btnSave.prop('disabled',false);
                btnSave.html('Simpan');
                swal({
                    type:"success",
                });
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                $("#myModal").modal('toggle');

                // reset
               // reset
                me[0].reset();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
               btnSave.prop('disabled',false);
            }
        });

    });

    function deleteData(id){
        swal({
          title: 'Hapus Data!',
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes'
        }).then(function () {
            processDelete(id)
        }, function (dismiss) {
          // dismiss can be 'cancel', 'overlay',
          // 'close', and 'timer'
          if (dismiss === 'cancel') {
            swal(
              'Cancelled',
              '',
              'error'
            )
          }
        })
    }

    function processDelete(id) {
        var url = '{{ url("product")}}' + '/' + id;
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            dataType: "json",
            url: url,
            type : "DELETE",
            data : {
                _token : $('meta[name="csrf-token"]').attr('content'),
                id : id
            },
            success: function(data){
                swal(
                  'Deleted!',
                  'Your file has been deleted.',
                  'success'
                )
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
            }
        });
    }
</script>
@endsection