routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');
# Operator
Route::resource('operator', 'OperatorController');
Route::post('operator/detail', 'OperatorController@detail');

# Product Type
Route::resource('product-type', 'ProductTypeController');
Route::post('product-type/detail', 'ProductTypeController@detail');

# Product
Route::resource('product', 'ProductController');
Route::post('product/detail', 'ProductController@detail');

# Sale
Route::resource('sale', 'SaleController');
Route::post('sale/detail', 'SaleController@detail');

# Purchase
Route::resource('purchase', 'PurchaseController');

app/Sale.php
<?php

namespace App;

use DB;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    use Uuids;

    public $incrementing = false;

   	public $fillable = ['product_id', 'qty', 'buy_price', 'sell_price', 'date'];

   	public function product()
   	{
   		return $this->belongsTo('App\Product');
   	}

   	public static function thisDay()
   	{
   		$data = DB::table('sales')
   					->select(DB::raw('(sell_price*qty) as subtotal'))
   					->first();
   		// return $data->subtotal;
            return $data;
   	}
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Sale;

use Yajra\Datatables\Datatables;

use Yajra\Datatables\Html\Builder;


class SaleController extends Controller
{  
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $data = Sale::with('product');
            return Datatables::of($data)
                ->addColumn('subtotal', function($sale){
                    return number_format($sale->sell_price * $sale->qty);
                })
                ->addColumn('profit', function($sale){
                        $subtotal_beli = $sale->buy_price * $sale->qty;
                        $subtotal_jual = $sale->sell_price * $sale->qty;
                        return number_format($subtotal_jual - $subtotal_beli);
                })
                ->addColumn('action', function($sale){
                return view('datatables._action', [
                    'id' =>$sale->id,
                    'url' => url('product'),
                    'edit' => false,
                ]);

                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data' => 'date', 'name'=>'date', 'title'=>'Tanggal'])
            ->addColumn(['data' => 'product.name', 'name'=>'product.name', 'title'=>'Produk'])
            ->addColumn(['data' => 'buy_price', 'name'=>'buy_price', 'title'=>'Harga Beli'])
            ->addColumn(['data' => 'sell_price', 'name'=>'sell_price', 'title'=>'Harga Jual'])
            ->addColumn(['data' => 'qty', 'name'=>'qty', 'title'=>'Qty'])
            ->addColumn(['data' => 'subtotal', 'name'=>'subtotal', 'title'=>'Subtotal'])
            ->addColumn(['data' => 'profit', 'name'=>'profit', 'title'=>'Profit'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);
        return view('sales.index')->with(compact('html'));
    }

    public function store(Request $request)
    {
        if ($request->ajax()) {
            $data = Sale::create([
                'product_id' => $request->product_id,
                'qty' => $request->qty,
                'buy_price' => $request->buy_price,
                'sell_price' => $request->sell_price,
                'date' => $request->date,
            ]);

            // add stock product
            $product = \App\Product::reduceStock($request->product_id, $request->qty);
            return $data;
        }
    }
    public function update(Request $request)
    {
        if ($request->ajax()) {
            $data = Sale::find($request->id);
            $data->product_id = $request->product_id;
            $data->qty = $request->qty;
            $data->buy_price = $request->buy_price;
            $data->sell_price = $request->sell_price;
            $data->date = $request->date;
            $data->save();

            return $data;
        }
    }

    public function detail(Request $request)
    {
        if ($request->ajax()) {
            $id = $request->input('id');
            $data = Sale::find($id);
            return $data;
        }
    }

    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {
            $data = Sale::destroy($request->id);
            if ($data) {
                return $data;
            }
        }
    }
}

resources/views/sales/_modal.blade.php
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
             <form id="modal-form">
                {{ csrf_field() }}
                <input type="hidden" name="id" id="id">
                <input type="hidden" name="form-type" id="form-type" value="add">
              <div class="form-group">
                <label for="name">Tanggal:</label>
                {!! Form::date('date', \Carbon\Carbon::now(), [
                    'class' => 'form-control'
                ]) !!}
              </div>
              <div class="form-group">
                <label for="name">Product:</label>
                {!! Form::select('product_id', [''=>'']+App\Product::pluck('name','id')->all(), null, [
                    'class'=>'js-selectize',
                    'placeholder' => 'Pilih Produk']) !!}
              </div>
              <div class="form-group">
                <label for="name">Qty:</label>
                {!! Form::number('qty', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>
              <div class="form-group">
                <label for="name">Harga Beli:</label>
                {!! Form::number('buy_price', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>
              <div class="form-group">
                <label for="name">Harga Jual:</label>
                {!! Form::number('sell_price', null, ['class'=>'form-control', 'min'=>0]) !!}
              </div>

            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-save">Simpan</button>
      </div>
    </div>

  </div>
</div>

resources/views/sales/index.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Data Penjualan &nbsp; <div class="btn btn-success btn-xs btn-add" style="margin-bottom: 10px;" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Tambah</div>
                </div>
                <div class="panel-body">
                     {!! $html->table(['class'=>'table-striped']) !!}
                </div>
            </div>
        </div>
    </div>
</div>
    @include('sales._modal')
@endsection

@section('script')
{!! $html->scripts() !!}
<script>
    var formType = $("#form-type");
    var inputName = $("[name=name]");
    var inputId = $("#id");
    var modalTitle  = $(".modal-title");
    var btnSave = $(".btn-save");
    var _token = $("[name=_token]").val();
    var me = $("#modal-form");

     // when adding some data
    $(".btn-add").click(function() {
        modalTitle.html("Tambah Data");
        me[0].reset();

        btnSave.prop('disabled', false);
        formType.val("add");
    });

    // when click edit button
    $(document).on("click", ".edit-modal", function () {
        btnSave.prop('disabled', false);
         var id     = $(this).data('id');
         formType.val('update');
         $.ajax({
            dataType: "json",
            url: "{{ url('sale/detail') }}",
            data: {
                id:id,
                _token: _token
            },
            type : "post",
            success: function(data){
                $("[name=name]").val(data.name);
                $("[name=product_id]").val(data.operator_id);
                $("[name=qty]").val(data.qty);
                $("[name=buy_price]").val(data.buy_price);
                $("[name=sell_price]").val(data.sell_price);
                inputId.val(data.id);
                modalTitle.html('Update '+data.name);
            }
        });

    });

    // process data
    btnSave.click(function() {

        btnSave.prop('disabled',true);
        btnSave.html('Sedang diproses..');
        url = "{{ route('sale.store') }}";
        method = 'post';
        if(formType.val() != "add") {
            url = "{{ url('sale/update') }}";
            method = 'put';
        }

        $.ajax({
            dataType: "json",
            url: url,
            data: me.serialize(),
            type : method,
            success: function(data){
                btnSave.prop('disabled',false);
                btnSave.html('Simpan');
                swal({
                    type:"success",
                });
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                $("#myModal").modal('toggle');

                // reset
               // reset
                me[0].reset();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
               btnSave.prop('disabled',false);
            }
        });

    });

    function deleteData(id){
        swal({
          title: 'Hapus Data!',
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes'
        }).then(function () {
            processDelete(id)
        }, function (dismiss) {
          // dismiss can be 'cancel', 'overlay',
          // 'close', and 'timer'
          if (dismiss === 'cancel') {
            swal(
              'Cancelled',
              '',
              'error'
            );
            btnSave.prop('disabled',false);
          }
        })
    }

    function processDelete(id) {
        var url = '{{ url("sale")}}' + '/' + id;
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            dataType: "json",
            url: url,
            type : "DELETE",
            data : {
                _token : $('meta[name="csrf-token"]').attr('content'),
                id : id
            },
            success: function(data){
                swal(
                  'Deleted!',
                  'Your file has been deleted.',
                  'success'
                )
                window.LaravelDataTables["dataTableBuilder"].ajax.reload();
            },
             error: function(xhr, textStatus, errorThrown){
               swal({
                type:"error",
                html:errorThrown
               });
            }
        });
    }

    // get product data
    // when click edit button
    $(document).on("change", "[name=product_id]", function () {
         var id     = $(this).val();
         alert("product id : " + id);
         $.ajax({
            dataType: "json",
            url: "{{ url('product/detail') }}",
            data: {
                id:id,
                _token: _token
            },
            type : "post",
            success: function(data){
                $("[name=buy_price]").val(data.buy_price);
                $("[name=sell_price]").val(data.sell_price);
            }
        });

    });
</script>
@endsection